version: '3.2'
services:
  hamapp:
    build: ./hamapp
    volumes:
      - ./hamapp/log:/var/log/hamcco
    env_file:
      - ./hamapp/hamcco/userlocal.env
  hamweb:
    build: ./hamweb
    ports:
      - "80:80"
    links:
      - hamapp:app
